/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 18:16:13 CEST 2019
 */

package org.objectweb.proactive.core.body;

import org.junit.Test;
import static org.junit.Assert.*;

public class HalfBody_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
