/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 12 17:46:22 CET 2018
 */

package org.objectweb.proactive.core.remoteobject;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class RemoteObjectSet_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.objectweb.proactive.core.remoteobject.RemoteObjectSet"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RemoteObjectSet_ESTest_scaffolding.class.getClassLoader() ,
      "org.objectweb.proactive.core.config.CentralPAPropertyRepository",
      "org.objectweb.proactive.core.ProtocolException",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils$1",
      "org.apache.log4j.or.ObjectRenderer",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.objectweb.proactive.core.config.PAProperties",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Level",
      "org.objectweb.proactive.core.config.PropertyListValidator",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category",
      "org.objectweb.proactive.core.config.PAPropertyLong",
      "org.objectweb.proactive.utils.ArgCheck",
      "org.objectweb.proactive.extensions.pnp.PNPConfig",
      "org.objectweb.proactive.core.body.request.Request",
      "org.objectweb.proactive.core.body.message.Message",
      "org.objectweb.proactive.core.config.PAPropertyBoolean",
      "org.apache.log4j.helpers.ThreadLocalMap",
      "org.apache.log4j.spi.RepositorySelector",
      "org.objectweb.proactive.core.config.PAProperty",
      "org.objectweb.proactive.core.remoteobject.RemoteRemoteObject",
      "org.objectweb.proactive.core.ssh.proxycommand.ProxyCommandConfig",
      "org.objectweb.proactive.core.config.PAPropertyString",
      "org.objectweb.proactive.core.remoteobject.RemoteObject",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.spi.Configurator",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectSet$NotYetExposedException",
      "org.apache.log4j.or.DefaultRenderer",
      "org.objectweb.proactive.extensions.pnpssl.PNPSslConfig",
      "org.objectweb.proactive.core.config.PAPropertyList",
      "org.objectweb.proactive.core.remoteobject.exception.UnknownProtocolException",
      "org.objectweb.proactive.core.UniqueID",
      "org.objectweb.proactive.core.config.PAPropertyImpl",
      "org.objectweb.proactive.extensions.pamr.PAMRConfig",
      "org.objectweb.proactive.core.config.Constants",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectSet",
      "org.apache.log4j.spi.ThrowableRendererSupport",
      "org.apache.log4j.PropertyConfigurator",
      "org.objectweb.proactive.core.remoteobject.InternalRemoteRemoteObject",
      "org.objectweb.proactive.core.ProActiveRuntimeException",
      "org.objectweb.proactive.core.util.log.ProActiveLogger",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.Hierarchy",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils$AdditionalProtocolsValidator",
      "org.objectweb.proactive.core.config.PAPropertyInteger",
      "org.objectweb.proactive.utils.OperatingSystem",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectSet$RemoteRemoteObjectException",
      "org.apache.log4j.MDC",
      "org.objectweb.proactive.core.config.PAPropertyAlias",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.RootLogger",
      "org.objectweb.proactive.core.config.ProActiveConfiguration",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils",
      "org.apache.log4j.spi.RendererSupport",
      "org.objectweb.proactive.core.ProActiveException",
      "org.objectweb.proactive.core.config.PAProperty$PropertyType",
      "org.apache.log4j.Priority",
      "org.objectweb.proactive.core.config.PAProperties$PAPropertiesLoaderSPI",
      "org.objectweb.proactive.core.config.ProActiveConfiguration$CustomProperties",
      "org.apache.log4j.spi.LoggerRepository",
      "org.objectweb.proactive.core.util.log.ProActiveLoggerFactory",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.helpers.OptionConverter"
    );
  } 
}
