/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 12 17:46:22 CET 2018
 */

package org.objectweb.proactive.core.remoteobject;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVFS = true, useJEE = true) 
public class RemoteObjectSet_ESTest extends RemoteObjectSet_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
