/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 18:27:28 CEST 2019
 */

package org.objectweb.proactive.core.body.future;

import org.junit.Test;
import static org.junit.Assert.*;

public class FuturePool_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
