/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jun 14 15:22:50 CEST 2018
 */

package org.objectweb.proactive.extensions.dataspaces.vfs;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class VFSSpacesMountManagerImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(VFSSpacesMountManagerImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.objectweb.proactive.extensions.dataspaces.exceptions.FileSystemException",
      "org.apache.log4j.or.ObjectRenderer",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.Logger",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceNotFoundException",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI",
      "org.apache.log4j.Level",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.WrongApplicationIdException",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.ConfigurationException",
      "org.apache.commons.vfs2.FileSystemException",
      "org.apache.log4j.helpers.ThreadLocalMap",
      "org.apache.log4j.spi.RepositorySelector",
      "org.objectweb.proactive.extensions.dataspaces.core.SpaceInstanceInfo",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI$1",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.log4j.CategoryKey",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl",
      "org.apache.log4j.spi.Configurator",
      "org.apache.log4j.or.DefaultRenderer",
      "org.objectweb.proactive.extensions.dataspaces.core.SpaceType",
      "org.objectweb.proactive.core.UniqueID",
      "org.objectweb.proactive.extensions.dataspaces.core.SpacesMountManager",
      "org.apache.log4j.spi.ThrowableRendererSupport",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.DataSpacesException",
      "org.apache.log4j.PropertyConfigurator",
      "org.objectweb.proactive.core.ProActiveRuntimeException",
      "org.objectweb.proactive.core.util.log.ProActiveLogger",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.Hierarchy",
      "org.objectweb.proactive.extensions.dataspaces.core.naming.SpacesDirectory",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.MalformedURIException",
      "org.apache.log4j.MDC",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.RootLogger",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceAlreadyRegisteredException",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.apache.commons.vfs2.FileObject",
      "org.apache.log4j.spi.RendererSupport",
      "org.objectweb.proactive.core.ProActiveException",
      "org.apache.log4j.Priority",
      "org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject",
      "org.apache.log4j.spi.LoggerRepository",
      "org.objectweb.proactive.core.util.log.ProActiveLoggerFactory",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.helpers.OptionConverter"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.objectweb.proactive.extensions.dataspaces.core.naming.SpacesDirectory", false, VFSSpacesMountManagerImpl_ESTest_scaffolding.class.getClassLoader()));
  }
}
