/*
 * This file was automatically generated by EvoSuite
 * Thu May 24 10:19:44 CEST 2018
 */

package org.sat4j.pb.constraints.pb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sat4j.core.VecInt;
import org.sat4j.minisat.constraints.cnf.Lits;
import org.sat4j.pb.constraints.pb.ConflictMapClause;
import org.sat4j.pb.constraints.pb.IDataStructurePB;
import org.sat4j.pb.constraints.pb.MinWatchPbLongCP;
import org.sat4j.pb.constraints.pb.WatchPbLongCP;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVFS = true, useJEE = true) 
public class ConflictMap_ESTest extends ConflictMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Lits lits0 = new Lits();
      IDataStructurePB iDataStructurePB0 = IDataStructurePB.TAUTOLOGY;
      WatchPbLongCP watchPbLongCP0 = MinWatchPbLongCP.normalizedWatchPbNew(lits0, iDataStructurePB0);
      ConflictMapClause conflictMapClause0 = new ConflictMapClause(watchPbLongCP0, 0, false);
      VecInt[] vecIntArray0 = new VecInt[9];
      VecInt vecInt0 = new VecInt(1799, 1);
      vecIntArray0[1] = vecInt0;
      conflictMapClause0.byLevel = vecIntArray0;
      // Undeclared exception!
      try { 
        conflictMapClause0.isAssertive(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("org.sat4j.core.Vec", e);
      }
  }
}
