/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 05 14:37:00 GMT 2019
 */

package org.objectweb.proactive.extensions.dataspaces.vfs;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class VFSSpacesMountManagerImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "FR"); 
    java.lang.System.setProperty("user.dir", "/home/mael/stamp/wp3/projects/scheduling"); 
    java.lang.System.setProperty("user.home", "/home/mael"); 
    java.lang.System.setProperty("user.language", "fr"); 
    java.lang.System.setProperty("user.name", "mael"); 
    java.lang.System.setProperty("user.timezone", "Europe/Paris"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(VFSSpacesMountManagerImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.objectweb.proactive.extensions.dataspaces.core.ScratchSpaceConfiguration",
      "org.hyperic.sigar.DirUsage",
      "org.apache.commons.vfs2.events.AbstractFileChangeEvent",
      "org.apache.commons.vfs2.impl.SynchronizedFileObject",
      "org.hyperic.sigar.SigarNotImplementedException",
      "org.apache.log4j.helpers.PatternConverter",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils$1",
      "org.objectweb.proactive.core.remoteobject.rmi.RmiRemoteObjectFactory",
      "org.apache.commons.logging.impl.SimpleLog",
      "org.apache.log4j.varia.FallbackErrorHandler",
      "org.objectweb.proactive.core.config.PAProperties",
      "org.apache.log4j.AppenderSkeleton",
      "org.apache.commons.vfs2.events.CreateEvent",
      "org.apache.commons.vfs2.provider.TemporaryFileStore",
      "org.hyperic.sigar.ProcTime",
      "org.hyperic.sigar.shell.ShellCommand_set",
      "com.jcraft.jsch.SftpException",
      "org.apache.commons.io.filefilter.EmptyFileFilter",
      "org.apache.log4j.Level",
      "org.apache.log4j.helpers.DateTimeDateFormat",
      "org.hyperic.sigar.ResourceLimit",
      "org.apache.commons.vfs2.provider.gzip.GzipFileSystem",
      "org.apache.log4j.helpers.QuietWriter",
      "org.apache.commons.logging.impl.AvalonLogger",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.log4j.ConsoleAppender$SystemOutStream",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.ConfigurationException",
      "org.apache.commons.vfs2.provider.http.HttpFileSystem",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.objectweb.proactive.extensions.dataspaces.core.naming.NamingService",
      "org.apache.commons.vfs2.provider.FileProvider",
      "org.apache.log4j.SimpleLayout",
      "org.apache.commons.vfs2.FileSystemException",
      "org.apache.log4j.helpers.ISO8601DateFormat",
      "org.apache.log4j.spi.Filter",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.hyperic.sigar.DiskUsage",
      "org.hyperic.sigar.NfsUnreachableException",
      "org.hyperic.sigar.ProcState",
      "org.apache.log4j.config.PropertySetter",
      "org.objectweb.proactive.extensions.dataspaces.core.SpaceInstanceInfo",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.vfs2.impl.DefaultVfsComponentContext",
      "org.hyperic.sigar.pager.PageFetchException",
      "org.apache.log4j.helpers.PatternParser$BasicPatternConverter",
      "org.apache.commons.net.ftp.Configurable",
      "org.hyperic.sigar.pager.StaticPageFetcher",
      "org.apache.log4j.Layout",
      "org.apache.commons.vfs2.AllFileSelector",
      "org.hsqldb.lib.FileUtil$DatabaseFilenameFilter",
      "com.jcraft.jsch.JSchException",
      "org.hyperic.sigar.cmd.Shell",
      "org.apache.commons.vfs2.provider.ram.RamFileOutputStream",
      "org.hyperic.sigar.NetConnection",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.log4j.varia.LevelMatchFilter",
      "org.hyperic.sigar.shell.ShellCommandInitException",
      "org.apache.commons.vfs2.provider.url.UrlFileSystem",
      "org.objectweb.proactive.core.ProActiveRuntimeException",
      "org.apache.log4j.Hierarchy",
      "org.apache.commons.vfs2.provider.FileSystemKey",
      "org.apache.commons.vfs2.provider.VfsComponentContext",
      "org.apache.log4j.helpers.PatternParser$CategoryPatternConverter",
      "org.apache.commons.vfs2.provider.ram.RamFileSystem",
      "org.apache.commons.vfs2.FileContentInfo",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "com.google.common.io.PatternFilenameFilter",
      "org.apache.commons.vfs2.FileSystemOptions",
      "org.hyperic.sigar.shell.SIGINT",
      "org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder$ProxyType",
      "org.objectweb.proactive.extensions.dataspaces.api.FileType",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.OptionHandler",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSFactory$ManagerType",
      "org.apache.commons.vfs2.provider.VfsComponent",
      "org.apache.commons.vfs2.util.WeakRefFileListener",
      "org.apache.commons.vfs2.impl.DecoratedFileObject",
      "org.apache.commons.vfs2.provider.zip.ZipFileSystem",
      "org.apache.commons.logging.impl.NoOpLog",
      "org.objectweb.proactive.extensions.dataspaces.core.SpaceConfiguration",
      "org.apache.commons.vfs2.FileObject",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils",
      "org.apache.commons.vfs2.events.DeleteEvent",
      "org.apache.commons.vfs2.provider.GenericFileName",
      "org.hyperic.sigar.shell.CollectionCompleter",
      "org.objectweb.proactive.core.config.PAProperty$PropertyType",
      "org.hyperic.sigar.Uptime",
      "org.apache.commons.vfs2.FileNotFoundException",
      "org.apache.commons.io.filefilter.WildcardFilter",
      "org.apache.commons.vfs2.FileType",
      "org.objectweb.proactive.extensions.dataspaces.api.DataSpacesFileObject",
      "org.apache.log4j.RollingFileAppender",
      "org.hyperic.sigar.Cpu",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.FormattingInfo",
      "org.apache.commons.vfs2.provider.ram.RamFileData",
      "org.hyperic.sigar.Sigar",
      "org.apache.commons.vfs2.provider.URLFileName",
      "org.apache.commons.vfs2.FileContentInfoFactory",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.hyperic.jni.ArchLoaderException",
      "com.jcraft.jsch.Channel",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepository",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectProtocolFactoryRegistry",
      "org.apache.commons.vfs2.provider.ram.RamFileObject",
      "org.apache.commons.vfs2.provider.webdav.WebdavFileSystem",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.net.ftp.FTP",
      "org.apache.commons.vfs2.operations.FileOperationProvider",
      "org.apache.log4j.EnhancedPatternLayout",
      "org.hyperic.sigar.Mem",
      "org.hyperic.sigar.ProcStat",
      "org.python.core.packagecache.PathPackageManager$PackageExistsFileFilter",
      "org.apache.log4j.or.ObjectRenderer",
      "org.apache.commons.vfs2.provider.AbstractFileSystem",
      "org.apache.commons.vfs2.provider.sftp.SftpFileSystem",
      "org.hyperic.sigar.CpuPerc",
      "org.apache.log4j.helpers.PatternParser$ClassNamePatternConverter",
      "org.apache.commons.vfs2.provider.DelegateFileObject",
      "org.hyperic.sigar.Who",
      "org.apache.commons.vfs2.FileSystemManager",
      "org.apache.commons.vfs2.CacheStrategy",
      "org.hyperic.sigar.shell.ShellCommandBase",
      "org.hyperic.sigar.shell.ShellCommandExecException",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI",
      "org.apache.commons.vfs2.provider.DefaultFileSelectorInfo",
      "org.objectweb.proactive.extensions.vfsprovider.client.ProActiveFileObject$DefaultFileSelectorInfo",
      "org.apache.commons.vfs2.cache.NullFilesCache",
      "org.apache.log4j.helpers.PatternParser",
      "org.apache.commons.vfs2.provider.bzip2.Bzip2FileSystem",
      "org.apache.log4j.AsyncAppender",
      "org.apache.log4j.Category",
      "org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder",
      "org.objectweb.proactive.utils.ArgCheck",
      "org.apache.commons.vfs2.provider.LayeredFileName",
      "org.hyperic.sigar.FileSystemUsage",
      "org.apache.commons.vfs2.cache.AbstractFilesCache",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.objectweb.proactive.extensions.dataspaces.api.FileContent",
      "org.apache.log4j.helpers.ThreadLocalMap",
      "org.hsqldb.lib.FileAccess",
      "org.objectweb.proactive.core.config.PAProperty",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "org.apache.log4j.helpers.RelativeTimeDateFormat",
      "org.hyperic.sigar.Tcp",
      "org.apache.commons.vfs2.FileName",
      "org.apache.commons.httpclient.HttpClient",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI$1",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.log4j.ConsoleAppender",
      "org.apache.commons.io.filefilter.FalseFileFilter",
      "org.apache.log4j.spi.Configurator",
      "org.hyperic.sigar.shell.ShellCommand_quit",
      "org.apache.commons.logging.impl.SLF4JLog",
      "org.apache.commons.logging.impl.Jdk14Logger",
      "org.apache.commons.vfs2.provider.compressed.CompressedFileFileSystem",
      "org.apache.log4j.spi.LocationInfo",
      "org.apache.commons.vfs2.cache.DefaultFilesCache",
      "org.hyperic.sigar.CpuInfo",
      "org.apache.log4j.TTCCLayout",
      "org.apache.log4j.varia.StringMatchFilter",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.DataSpacesException",
      "org.objectweb.proactive.core.util.log.ProActiveLogger",
      "org.objectweb.proactive.core.util.ProActiveInet",
      "org.apache.log4j.helpers.PatternParser$NamedPatternConverter",
      "org.hyperic.sigar.pager.PageControl",
      "org.apache.commons.vfs2.impl.DefaultFileSystemConfigBuilder",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.vfs2.FileSelectInfo",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.MalformedURIException",
      "org.apache.commons.httpclient.HttpException",
      "org.objectweb.proactive.extensions.dataspaces.core.naming.SpacesDirectoryImpl",
      "org.apache.log4j.HTMLLayout",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectFactorySPI",
      "org.apache.commons.vfs2.FileListener",
      "org.hyperic.sigar.SigarException",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceAlreadyRegisteredException",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.apache.log4j.helpers.PatternParser$DatePatternConverter",
      "org.apache.log4j.helpers.PatternParser$MDCPatternConverter",
      "org.apache.commons.vfs2.provider.hdfs.HdfsFileSystem",
      "org.apache.log4j.Priority",
      "org.objectweb.proactive.extensions.dataspaces.core.naming.CachingSpacesDirectory",
      "org.apache.log4j.FileAppender",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.config.PropertySetterException",
      "org.objectweb.proactive.core.util.log.ProActiveLoggerFactory",
      "org.apache.commons.vfs2.provider.FileLockStrategyFactory",
      "org.apache.commons.vfs2.provider.jar.JarFileSystem",
      "org.hyperic.sigar.shell.ShellCommand_sleep",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "org.hyperic.sigar.NfsServerV3",
      "org.apache.commons.vfs2.FileContent",
      "org.hyperic.sigar.NfsServerV2",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.FileSystemException",
      "org.apache.commons.vfs2.FileChangeEvent",
      "org.hsqldb.lib.FileUtil",
      "org.apache.commons.vfs2.FileNotFolderException",
      "org.apache.commons.vfs2.FileSelector",
      "org.hyperic.sigar.shell.ShellCommand_get",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.hyperic.sigar.FileSystem",
      "org.apache.commons.vfs2.impl.DefaultFileSystemManager",
      "org.apache.commons.httpclient.URIException",
      "org.apache.log4j.or.RendererMap",
      "org.apache.commons.vfs2.provider.ftp.FtpClient",
      "org.objectweb.proactive.extensions.dataspaces.vfs.DefaultOptionsFileSystemManager",
      "org.hyperic.sigar.SigarLoader",
      "org.hyperic.sigar.shell.MultiwordShellCommand",
      "org.apache.log4j.ConsoleAppender$SystemErrStream",
      "org.hyperic.sigar.MultiProcCpu",
      "org.apache.log4j.pattern.BridgePatternParser",
      "org.objectweb.proactive.core.config.PropertyListValidator",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.objectweb.proactive.core.config.PAPropertyLong",
      "org.hyperic.sigar.shell.FileCompleter",
      "org.apache.commons.vfs2.provider.ftp.FTPClientWrapper",
      "org.objectweb.proactive.core.config.PAPropertyBoolean",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "org.hyperic.sigar.NetRoute",
      "org.apache.commons.vfs2.FileFilter",
      "org.hyperic.sigar.FileInfo",
      "org.apache.commons.logging.impl.Jdk13LumberjackLogger",
      "org.objectweb.proactive.core.config.PAPropertyString",
      "org.apache.commons.vfs2.provider.ftps.FtpsClientWrapper",
      "org.objectweb.proactive.core.remoteobject.rmissh.RmiSshRemoteObjectFactory",
      "org.apache.log4j.helpers.PatternParser$LocationPatternConverter",
      "com.jcraft.jsch.Session",
      "org.apache.log4j.RollingCalendar",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.WriterAppender",
      "org.hyperic.sigar.Swap",
      "org.objectweb.proactive.core.config.PAPropertyList",
      "org.hyperic.sigar.util.GetlineCompleter",
      "org.apache.log4j.varia.DenyAllFilter",
      "org.apache.log4j.helpers.DateLayout",
      "org.objectweb.proactive.core.config.PAPropertyImpl",
      "org.apache.log4j.helpers.OnlyOnceErrorHandler",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.hyperic.sigar.NetStat",
      "org.apache.commons.vfs2.provider.zip.ZipFileObject",
      "org.objectweb.proactive.extensions.dataspaces.core.SpacesMountManager",
      "org.apache.commons.vfs2.FileFilterSelector",
      "org.apache.commons.vfs2.provider.DefaultURLStreamHandler",
      "org.hyperic.sigar.pager.PageFetcher",
      "org.apache.log4j.helpers.Loader",
      "org.hyperic.sigar.shell.NormalQuitCommandException",
      "org.hyperic.sigar.NetInterfaceConfig",
      "org.apache.log4j.ProvisionNode",
      "org.apache.commons.vfs2.PatternFileSelector",
      "org.hyperic.sigar.PFlags",
      "org.hyperic.sigar.ProcExe",
      "org.apache.commons.vfs2.events.ChangedEvent",
      "org.hyperic.sigar.ptql.ProcessFinder",
      "org.apache.commons.vfs2.provider.ftp.FtpFileSystem",
      "org.apache.commons.vfs2.cache.SoftRefFilesCache",
      "org.hyperic.sigar.FileSystemMap",
      "org.hyperic.sigar.shell.ShellCommand_source",
      "org.apache.log4j.MDC",
      "org.objectweb.proactive.core.remoteobject.AbstractRemoteObjectFactory",
      "org.apache.log4j.helpers.PatternParser$LiteralPatternConverter",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.commons.logging.impl.SLF4JLocationAwareLog",
      "org.objectweb.proactive.core.remoteobject.rmi.AbstractRmiRemoteObjectFactory",
      "org.apache.log4j.spi.ErrorHandler",
      "org.hyperic.sigar.NetInterfaceStat",
      "org.apache.log4j.spi.RendererSupport",
      "org.apache.commons.vfs2.FileSystemOptions$FileSystemOptionKey",
      "org.apache.commons.vfs2.UserAuthenticationData",
      "org.hyperic.sigar.NfsClientV3",
      "org.hyperic.sigar.NfsClientV2",
      "org.apache.commons.vfs2.Capability",
      "org.apache.commons.vfs2.provider.AbstractFileObject",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "org.apache.log4j.helpers.AppenderAttachableImpl",
      "org.objectweb.proactive.annotation.PublicAPI",
      "org.apache.commons.vfs2.cache.OnCallRefreshFileObject",
      "com.jcraft.jsch.ChannelSession",
      "org.hyperic.sigar.shell.ShellCommand_alias",
      "org.objectweb.proactive.extensions.dataspaces.vfs.adapter.VFSFileObjectAdapter",
      "org.apache.commons.vfs2.FileSystem",
      "org.apache.commons.vfs2.util.RandomAccessMode",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.ApplicationAlreadyRegisteredException",
      "org.hyperic.sigar.shell.ShellBase",
      "org.hyperic.sigar.ProcCredName",
      "org.objectweb.proactive.extensions.dataspaces.core.InputOutputSpaceConfiguration",
      "org.apache.commons.vfs2.NameScope",
      "org.objectweb.proactive.extensions.dataspaces.api.FileSelector",
      "org.hyperic.sigar.DirStat",
      "org.hyperic.sigar.ProcCred",
      "org.apache.log4j.helpers.AbsoluteTimeDateFormat",
      "org.objectweb.proactive.extensions.dataspaces.api.Capability",
      "org.objectweb.proactive.core.remoteobject.http.HTTPRemoteObjectFactory",
      "org.apache.log4j.varia.LevelRangeFilter",
      "org.apache.log4j.Logger",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSFactory",
      "org.hyperic.sigar.ProcFd",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceNotFoundException",
      "org.hyperic.sigar.shell.ShellCommandUsageException",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.WrongApplicationIdException",
      "org.hyperic.sigar.FileAttrs",
      "org.hyperic.sigar.pager.ListPageFetcher",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper",
      "org.apache.commons.vfs2.FileExtensionSelector",
      "org.apache.commons.net.ftp.FTPClient",
      "org.apache.commons.vfs2.provider.ftps.FtpsFileSystem",
      "org.apache.log4j.helpers.LogLog",
      "org.hyperic.sigar.NetInfo",
      "org.apache.commons.vfs2.RandomAccessContent",
      "org.apache.commons.vfs2.FilesCache",
      "org.apache.log4j.spi.RepositorySelector",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "org.hyperic.sigar.ProcMem",
      "org.hyperic.sigar.shell.ShellCommand_help",
      "org.apache.commons.vfs2.provider.AbstractFileName",
      "org.apache.log4j.DailyRollingFileAppender",
      "org.apache.commons.vfs2.provider.AbstractVfsComponent",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl",
      "org.apache.commons.vfs2.FileDepthSelector",
      "org.apache.commons.net.ftp.FTPFile",
      "org.apache.log4j.or.DefaultRenderer",
      "org.objectweb.proactive.extensions.dataspaces.core.SpaceType",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.objectweb.proactive.core.UniqueID",
      "org.apache.commons.vfs2.FileTypeSelector",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectFactory",
      "org.objectweb.proactive.extensions.vfsprovider.client.ProActiveFileObject$TraverseFilesTask",
      "org.hyperic.sigar.util.Getline",
      "org.apache.commons.io.IOCase",
      "org.objectweb.proactive.core.config.Constants",
      "org.apache.commons.vfs2.cache.WeakRefFilesCache",
      "org.apache.commons.vfs2.impl.VirtualFileName",
      "org.apache.log4j.spi.ThrowableRendererSupport",
      "org.apache.log4j.PropertyConfigurator",
      "org.hyperic.jni.ArchNotSupportedException",
      "org.hyperic.sigar.ThreadCpu",
      "org.apache.commons.logging.impl.Log4JLogger",
      "org.apache.commons.vfs2.provider.tar.TarFileSystem",
      "org.apache.commons.vfs2.provider.FileReplicator",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils$AdditionalProtocolsValidator",
      "org.objectweb.proactive.extensions.dataspaces.core.naming.SpacesDirectory",
      "org.apache.log4j.Appender",
      "org.apache.commons.net.SocketClient",
      "org.apache.commons.vfs2.provider.local.LocalFileSystem",
      "org.apache.commons.vfs2.operations.FileOperations",
      "org.objectweb.proactive.core.config.PAPropertyInteger",
      "org.hyperic.sigar.shell.ShellCommandMapper",
      "com.jcraft.jsch.ChannelSftp",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "org.apache.log4j.helpers.CountingQuietWriter",
      "org.objectweb.proactive.extensions.annotation.RemoteObject",
      "org.apache.log4j.SortedKeyEnumeration",
      "org.apache.commons.vfs2.cache.LRUFilesCache",
      "org.hyperic.sigar.SigarProxy",
      "org.apache.log4j.spi.LoggingEvent",
      "org.hyperic.sigar.pager.PageList",
      "org.apache.commons.vfs2.FileSystemConfigBuilder",
      "org.apache.commons.vfs2.provider.jar.JarFileObject",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.hyperic.sigar.shell.ShellCommandHandler",
      "org.objectweb.proactive.core.ProActiveException",
      "org.apache.commons.logging.impl.LogKitLogger",
      "org.apache.log4j.spi.ThrowableInformation",
      "org.objectweb.proactive.core.config.PAProperties$PAPropertiesLoaderSPI",
      "org.hyperic.jni.ArchLoader",
      "org.hyperic.sigar.ProcCpu",
      "org.apache.log4j.spi.LoggerRepository",
      "org.apache.log4j.PatternLayout",
      "org.objectweb.proactive.extensions.vfsprovider.client.ProActiveFileObject"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.objectweb.proactive.extensions.dataspaces.core.naming.SpacesDirectory", false, VFSSpacesMountManagerImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(VFSSpacesMountManagerImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.objectweb.proactive.core.util.log.ProActiveLogger",
      "org.objectweb.proactive.core.config.Constants",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.Priority",
      "org.apache.log4j.Level",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.ConsoleAppender",
      "org.apache.log4j.Layout",
      "org.apache.log4j.PatternLayout",
      "org.apache.log4j.helpers.PatternParser",
      "org.apache.log4j.helpers.PatternConverter",
      "org.apache.log4j.config.PropertySetter",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.MDC",
      "org.objectweb.proactive.core.UniqueID",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl",
      "org.objectweb.proactive.core.util.ProActiveInet",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSMountManagerHelper",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSFactory$ManagerType",
      "org.apache.commons.logging.impl.Log4JLogger",
      "org.objectweb.proactive.extensions.dataspaces.vfs.VFSFactory",
      "org.apache.commons.vfs2.FileSystemConfigBuilder",
      "org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder$ProxyType",
      "org.apache.commons.vfs2.provider.sftp.SftpFileSystemConfigBuilder",
      "org.objectweb.proactive.core.config.PAProperty$PropertyType",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepository",
      "org.objectweb.proactive.core.config.CentralPAPropertyRepositoryUtils",
      "org.apache.commons.vfs2.CacheStrategy",
      "org.apache.log4j.spi.LoggingEvent",
      "org.objectweb.proactive.core.remoteobject.RemoteObjectProtocolFactoryRegistry",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI",
      "org.objectweb.proactive.extensions.dataspaces.core.DataSpacesURI$1",
      "org.objectweb.proactive.core.ProActiveException",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.DataSpacesException",
      "org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceNotFoundException"
    );
  }
}
