/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 31 16:59:31 CET 2018
 */

package org.apache.axis2.description;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient_ESTest extends RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
