/*
 * This file was automatically generated by EvoSuite
 * Fri May 03 10:20:42 CEST 2019
 */

package org.objectweb.proactive.core.body.request;

import org.junit.Test;
import static org.junit.Assert.*;

public class RequestImpl_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
